spring:
  application:
    name: EurekaService9002  # 服务端的实例名称
server:
  port: 9002
eureka:
  instance:
    hostname: www.registerCenterTwo.com #localhostEurekaServiceComputer
    prefer-ip-address: true #显示服务的IP地址
  client:
    register-with-eureka: false
    #注册中心注册服务,服务提供者注册服务
    #注册中心负责提供服务注册和服务发现的服务,不用将自己注册到注册中心
    fetch-registry: false
    #注册中心不用获取服务,消费者获取服务
    #fetch-registry为false则表示自己为注册中心
    service-url:
      #提供服务注册与发现的地址,集群是可以写多个
      #单机配置 defaultZone: http://${eureka.instance.hostname}:${server.port}/erueka/

      #集群配置
      defaultZone: http://www.registerCenterOne.com:9001/eureka/,http://www.registerCenterTwo.com:9002/eureka/,http://www.registerCenterThree.com:9003/eureka/

debug: true
